import type { Metadata } from "next";
import "../globals.css";
import { SessionProvider } from "next-auth/react";
import { CvWizardProvider } from "@/context/CvWizardContext";
import CustomCursorPage from "@/components/ui/neoncursor";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en" className="scroll-smooth dark">
      <body>
      <CvWizardProvider>
       <SessionProvider>
      <CustomCursorPage />  
        {children}
        </SessionProvider> 
      </CvWizardProvider>
      </body>
    </html>
  );
}
