import type { Metadata } from "next";
import "../globals.css";
import { SessionProvider } from "next-auth/react";
import { CvWizardProvider } from "@/context/CvWizardContext";
import CustomCursorPage from "@/components/ui/neoncursor";
import { Analytics } from "@vercel/analytics/next";

const siteUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "CvWizardAI | CV Generated By AI",
  description: "CV Generated By AI",
  openGraph: {
    title: "CvWizardAI | CV Generated By AI",
    description: "CV Generated By AI",
    url: "/",
    siteName: "CvWizardAI",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "CvWizardAI",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "CvWizardAI | CV Generated By AI",
    description: "CV Generated By AI",
    images: ["/og-image.png"],
  },
  other: {
    "google-site-verification": "LnKdFIUnYiWkSAZ8gLFRBvsFmk4Ddg2yrL92uMva9cc",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en" className="scroll-smooth dark">
      <link rel="icon" href="./favicon.ico" type="image/x-icon"></link>
      <body>
      <CvWizardProvider>
       <SessionProvider>
      <CustomCursorPage />  
        {children}
        <Analytics />
        </SessionProvider> 
      </CvWizardProvider>
      </body>
    </html>
  );
}
